/* eslint-disable prettier/prettier */
// GET COMING SOON MOVIES
export const FETCH_COMING_SOON_MOVIES = 'FETCH_COMING_SOON_MOVIES';
export const FETCH_COMING_SOON_MOVIES_FAILED =
  'FETCH_COMING_SOON_MOVIES_FAILED';
export const SET_COMING_SOON_MOVIES = 'SET_COMING_SOON_MOVIES';
