/* eslint-disable prettier/prettier */
//FETCH MOVIES ACTIONS
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const FETCH_ALL_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
//FETCH ONE MOVIE
export const FETCH_MOVIE_BY_ID = 'FETCH_MOVIE_BY_ID';
export const SET_MOVIE = 'FETCH_MOVIE_BY_ID';
export const FETCH_MOVIE_BY_ID_FAILED = 'FETCH_MOVIE_BY_ID_FAILED';
// LIST CONSTANTS
export const REFRESH = 'REFRESH';
export const LOADING_MORE = 'LOADING_MORE';
export const CHANGE_TITLE = 'CHANGE_TITLE';
// SEARCH
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_SORT_OPTION = 'CHANGE_SORT_OPTION';
export const CHANGE_GENRES = 'CHANGE_GENRES';
// GET BY GENRE TOP
export const FETCH_TOP_MOVIES_BY_GENRE = 'FETCH_TOP_MOVIES_BY_GENRE';
export const FETCH_TOP_MOVIES_BY_GENRE_FAILED =
  'FETCH_TOP_MOVIES_BY_GENRE_FAILED';
export const SET_TOP_MOVIES_BY_GENRE = 'SET_TOP_MOVIES_BY_GENRE';
//GENRES
export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_GENRES_FAILED = 'FETCH_GENRES_FAILED';
export const SET_GENRES = 'SET_GENRES';
//MOVIES BY GENRE
export const FETCH_MOVIES_BY_GENRE = 'FETCH_MOVIES_BY_GENRE';
export const FETCH_MOVIES_BY_GENRE_FAILED = 'FETCH_MOVIES_BY_GENRE_FAILED';
export const SET_MOVIES_BY_GENRE = 'SET_MOVIES_BY_GENRE';
//GET TOP 100 MOVIES
export const FETCH_TOP_100 = 'FETCH_TOP_100';
export const FETCH_TOP_100_FAILED = 'FETCH_TOP_100_FAILED';
export const SET_TOP_100 = 'SET_TOP_100';
//RATE MOVIE
export const RATE_MOVIE = 'RATE_MOVIE';
export const RATE_MOVIE_FAILED = 'RATE_MOVIE_FAILED';
//GET RECOMMENDED MOVIES
export const FETCH_RECOMMENDED_MOVIES = 'FETCH_RECOMMENDED_MOVIES';
export const FETCH_RECOMMENDED_MOVIES_FAILED =
  'FETCH_RECOMMENDED_MOVIES_FAILED';
export const SET_RECOMMENDED_MOVIES = 'SET_RECOMMENDED_MOVIES';
//GET DETAIL RECOMMENDED MOVIES
export const FETCH_DETAIL_RECOMMENDED_MOVIES =
  'FETCH_DETAIL_RECOMMENDED_MOVIES';
export const FETCH_DETAIL_RECOMMENDED_MOVIES_FAILED =
  'FETCH_DETAIL_RECOMMENDED_MOVIES_FAILED';
export const SET_DETAIL_RECOMMENDED_MOVIES = 'SET_DETAIL_RECOMMENDED_MOVIES';
export const CLEAR_MOVIE = 'CLEAR_MOVIE';
// GET REVIEWS
export const FETCH_REVIEWS = 'FETCH_REVIEWS';
export const FETCH_REVIEWS_FAILED = 'FETCH_REVIEWS_FAILED';
export const SET_REVIEWS = 'SET_REVIEWS';
// REVIEW MOVIE
export const REVIEW_MOVIE = 'REVIEW_MOVIE';
export const REVIEW_MOVIE_FAILED = 'REVIEW_MOVIE_FAILED';
// ADD TO MY LIST
export const ADD_TO_MY_LIST = 'ADD_TO_MY_LIST';
export const ADD_TO_MY_LIST_FAILED = 'ADD_TO_MY_LIST_FAILED';
//GET NOW PLAYING MOVIES
export const FETCH_NOW_MOVIES = 'FETCH_NOW_MOVIES';
export const FETCH_NOW_MOVIES_FAILED = 'FETCH_NOW_MOVIES_FAILED';
export const SET_NOW_MOVIES = 'SET_NOW_MOVIES';
