/* eslint-disable prettier/prettier */
//FETCH MOVIES ACTIONS
export const FETCH_ALL_MOVIES = 'FETCH_ALL_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const FETCH_ALL_MOVIES_FAILED = 'FETCH_ALL_MOVIES_FAILED';
export const CLEAR_MOVIES = 'CLEAR_MOVIES';
// LIST CONSTANTS
export const REFRESH = 'REFRESH';
export const LOADING_MORE = 'LOADING_MORE';
export const CHANGE_TITLE = 'CHANGE_TITLE';
// SEARCH
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_SORT_OPTION = 'CHANGE_SORT_OPTION';
export const CHANGE_GENRES = 'CHANGE_GENRES';
